title: "Leonardo Cuellar"
description: "MIS & Accounting | Cloud | Data | Consulting"
url: "https://leonardocuellargold.github.io"
baseurl: ""
# Pick light accent colors you like
accent_color: "#ffd6e7" # light pink accent
text_color:   "#111111"

# Theme & plugins
remote_theme: jekyll/minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme

# Minima options
minima:
  social_links:
    - { platform: linkedin,   user_url: "https://www.linkedin.com/in/leonardo-gold" }
    - { platform: github,     user_url: "https://github.com/leonardocuellargold" }
    - { platform: x,          user_url: "https://x.com/le0nardo_gold" }

# Collections & Blog
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  projects:
    output: true
    permalink: /projects/:name/

# Blog defaults
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "Leonardo Cuellar"
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "project"

# Navigation (reordered per user request)
nav:
  - title: "Home"
    url: "/"
  - title: "Experience"
    url: "/experience/"
  - title: "Projects"
    url: "/projects/"
  - title: "Blog"
    url: "/blog/"
  - title: "Certifications"
    url: "/certifications/"
  - title: "About"
    url: "/about/"
  - title: "Contact"
    url: "/contact/"

# Build
markdown: kramdown
kramdown:
  input: GFM

# SASS/SCSS Configuration
sass:
  sass_dir: _sass
  style: compressed

# SEO
author: "Leonardo Cuellar"
lang: "en"
